import 'dart:math';
import 'github_service.dart';
import 'file_generator.dart';
import 'logger_service.dart';
import 'ai_service.dart';
import '../models/commit_record.dart';

class SessionEngine {
  final GitHubService _github = GitHubService();
  final LoggerService _logger = LoggerService();
  final AiService _ai = AiService();
  final Random _random = Random();

  Future<void> runSession({
    required String token,
    required String owner,
    required String repo,
    required int commitCount,
    String? apiKey,
    bool enableProWorkflows = false,
    Function(int)? onProgress,
    Function(CommitRecord)? onCommit,
  }) async {
    _logger.log('Session Start: $commitCount pulses scheduled.', type: LogType.info);

    String currentBranch = 'main';
    bool inFeatureBranch = false;
    int featureCommitCount = 0;

    for (int i = 0; i < commitCount; i++) {
      // 1. Pro Workflow Logic: Randomly start a feature branch
      if (enableProWorkflows && !inFeatureBranch && _random.nextDouble() > 0.7) {
        final featureName = _generateFeatureName();
        _logger.log('Pro Workflow: Branching to feature/$featureName', type: LogType.info);
        final branched = await _github.createBranch(token, owner, repo, 'feature/$featureName', 'main');
        if (branched) {
          currentBranch = 'feature/$featureName';
          inFeatureBranch = true;
          featureCommitCount = 0;
        }
      }

      final isNewFile = _random.nextBool();
      final ext = FileGenerator.getRandomExtension();
      String path;
      String content;
      String message;

      if (isNewFile) {
        path = FileGenerator.generateFileName(ext);
        message = _generateMessage('add', path);
        
        if (apiKey != null) {
          _logger.log('Intelligence Engine: Analyzing context for $path...', type: LogType.api);
          final aiContent = await _ai.generateContent(
            apiKey: apiKey, 
            prompt: _ai.buildCodePrompt(ext)
          );
          content = aiContent ?? FileGenerator.generateContent(ext);
        } else {
          content = FileGenerator.generateContent(ext);
        }
      } else {
        path = 'src/app_logic.$ext';
        message = _generateMessage('fix', path);
        
        if (apiKey != null) {
          _logger.log('Intelligence Engine: Generating deep analysis/fix...', type: LogType.api);
          final aiContent = await _ai.generateContent(
            apiKey: apiKey, 
            prompt: _ai.buildAnalysisPrompt()
          );
          content = aiContent ?? FileGenerator.generateContent(ext);
        } else {
          content = FileGenerator.generateContent(ext);
        }
      }

      final success = await _github.createOrUpdateFile(
        token: token,
        owner: owner,
        repo: repo,
        path: path,
        content: content,
        message: message,
        branch: currentBranch == 'main' ? null : currentBranch,
      );

      if (success) {
        if (inFeatureBranch) featureCommitCount++;
        
        final record = CommitRecord(
          path: path,
          message: message,
          timestamp: DateTime.now(),
          isSuccess: true,
        );
        onCommit?.call(record);
        onProgress?.call(i + 1);

        // 3. Pro Workflow: If in feature branch and have enough commits, open and merge PR
        if (enableProWorkflows && inFeatureBranch && featureCommitCount >= 2) {
          _logger.log('Pro Workflow: Finalizing feature. Opening Pull Request...', type: LogType.info);
          final prNumber = await _github.createPullRequest(
            token, owner, repo, 
            'Feature: Auto-implementation of $currentBranch',
            'This PR was automatically generated by DevSim AI to simulate feature development workflows.',
            currentBranch, 'main'
          );

          if (prNumber != null) {
            _logger.log('Pro Workflow: PR #$prNumber opened. Authenticating merge...', type: LogType.success);
            await Future.delayed(const Duration(seconds: 3)); // Realistic delay
            final merged = await _github.mergePullRequest(token, owner, repo, prNumber);
            if (merged) {
              _logger.log('Pro Workflow: PR #$prNumber merged into main.', type: LogType.success);
              currentBranch = 'main';
              inFeatureBranch = false;
            }
          }
        }
      } else {
        _logger.log('Session Sync Error. Terminating pulse.', type: LogType.error);
        break;
      }

      if (i < commitCount - 1) {
        final delaySeconds = _random.nextInt(15) + 10;
        await Future.delayed(Duration(seconds: delaySeconds));
      }
    }

    _logger.log('Session pulse completed.', type: LogType.success);
  }

  String _generateFeatureName() {
    final names = ['auth-refactor', 'ui-overhaul', 'api-integration', 'data-sync-fix', 'localization', 'payment-gateway', 'performance-patch'];
    return names[_random.nextInt(names.length)];
  }

  String _generateMessage(String type, String path) {
    final fixMessages = ['refactor: optimize data flow', 'fix: resolve race condition', 'docs: update module overview', 'perf: reduce memory footprint'];
    final addMessages = ['feat: implement $path core', 'init: setup module $path', 'build: configure CI for $path'];
    final list = type == 'fix' ? fixMessages : addMessages;
    return list[_random.nextInt(list.length)];
  }
}
